### ISSUE TITLE
多类别训练问题

### ISSUE THREAD

**Issue by stevenXS** [ZeroE04/R-CenterNet#8]
请问 多类别训练，除了更改num_classes变量，还需要更改其他的吗？

**Comment by ZeroE04** [comment]
> 请问 多类别训练，除了更改num_classes变量，还需要更改其他的吗？

还有最后显示框的颜色，现在只有一种框，红蓝框。

**Comment by stevenXS** [comment]
不好意思，我们目前还未解决多类别这个问题！-----当我们修改num_classes>1时，最终预测类别Id一直等于2，mAP一直处于0.4以下，若您解决了这些问题，欢迎交流！

**Comment by ZeroE04** [comment]
> 不好意思，我们目前还未解决多类别这个问题！-----当我们修改num_classes>1时，最终预测类别Id一直等于2，mAP一直处于0.4以下，若您解决了这些问题，欢迎交流！

你们标签打的是多类别的标签吗？我上传了生成训练标签的代码，您可以参考一下：
https://github.com/ZeroE04/R-CenterNet/tree/master/labelGenerator
如果还有问题，我周末找时间看一下。

**Comment by zzyx1215** [comment]
你好，我多类别训练完成后也出现了这个问题，请问有什么更改方法吗

**Comment by stevenXS** [comment]
@zzyx1215 目前尚无解决方法，猜测是mAP 或者网络本身输出结果计有误，

**Comment by Small93** [comment]
> 不好意思，我们目前还未解决多类别这个问题！-----当我们修改num_classes>1时，最终预测类别Id一直等于2，mAP一直处于0.4以下，若您解决了这些问题，欢迎交流！

我现在也是遇到这种问题，不知道你解决了没有

**Comment by zzyx1215** [comment]
> > 不好意思，我们目前还未解决多类别这个问题！-----当我们修改num_classes>1时，最终预测类别Id一直等于2，mAP一直处于0.4以下，若您解决了这些问题，欢迎交流！
> 
> 我现在也是遇到这种问题，不知道你解决了没有

现在我解决了多类别问题，在你所使用的backbone的网络代码中将hm更改为你的类别数，之后将其他地方的num_class更改你的类别数，就可以了

**Comment by Small93** [comment]
> > > 不好意思，我们目前还未解决多类别这个问题！-----当我们修改num_classes>1时，最终预测类别Id一直等于2，mAP一直处于0.4以下，若您解决了这些问题，欢迎交流！
> > 
> > 
> > 我现在也是遇到这种问题，不知道你解决了没有
> 
> 现在我解决了多类别问题，在你所使用的backbone的网络代码中将hm更改为你的类别数，之后将其他地方的num_class更改你的类别数，就可以了

现在能够正常训练、测试多类别了，谢谢

**Comment by Small93** [comment]
> > > 不好意思，我们目前还未解决多类别这个问题！-----当我们修改num_classes>1时，最终预测类别Id一直等于2，mAP一直处于0.4以下，若您解决了这些问题，欢迎交流！
> > 
> > 
> > 我现在也是遇到这种问题，不知道你解决了没有
> 
> 现在我解决了多类别问题，在你所使用的backbone的网络代码中将hm更改为你的类别数，之后将其他地方的num_class更改你的类别数，就可以了

嗯嗯，现在类别数正常了，谢谢

**Comment by gengyanlei** [comment]
num_classes都出现在哪些位置呢？

**Comment by Z-ztao** [comment]
请问map值怎么测试得到的

**Comment by Z-ztao** [comment]
请问多目标训练后，map是怎么得到的，怎么修改evaluation.py文件呐

**Comment by singlestrong** [comment]
> > > 不好意思，我们目前还未解决多类别这个问题！-----当我们修改num_classes>1时，最终预测类别Id一直等于2，mAP一直处于0.4以下，若您解决了这些问题，欢迎交流！
> > 
> > 
> > 我现在也是遇到这种问题，不知道你解决了没有
> 
> 现在我解决了多类别问题，在你所使用的backbone的网络代码中将hm更改为你的类别数，之后将其他地方的num_class更改你的类别数，就可以了

请问你们的map是怎么计算的，又代码提供吗？实在实现不了

**Comment by Z-ztao** [comment]
这样就行了。感觉计算旋转map又要另外的方法



| |
sunshinetaoz
|
|
***@***.***
|
发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月26日 14:49 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ZeroE04/R-CenterNet] 多类别训练问题 (#8) |

不好意思，我们目前还未解决多类别这个问题！-----当我们修改num_classes>1时，最终预测类别Id一直等于2，mAP一直处于0.4以下，若您解决了这些问题，欢迎交流！

我现在也是遇到这种问题，不知道你解决了没有

现在我解决了多类别问题，在你所使用的backbone的网络代码中将hm更改为你的类别数，之后将其他地方的num_class更改你的类别数，就可以了

请问你们的map是怎么计算的，又代码提供吗？实在实现不了

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by singlestrong** [comment]
请问你成功计算了MAP吗？？可以提供代码吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZeroE04/R-CenterNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月26日(星期五) 下午2:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZeroE04/R-CenterNet] 多类别训练问题 (#8)





 这样就行了。感觉计算旋转map又要另外的方法
 
 
 
 | |
 sunshinetaoz
 |
 |
 ***@***.***
 |
 发自 网易邮箱大师
 
 
 
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 日期 | 2021年11月26日 14:49 |
 | 收件人 | ***@***.***&gt; |
 | 抄送至 | ***@***.******@***.***&gt; |
 | 主题 | Re: [ZeroE04/R-CenterNet] 多类别训练问题 (#8) |
 
 不好意思，我们目前还未解决多类别这个问题！-----当我们修改num_classes&gt;1时，最终预测类别Id一直等于2，mAP一直处于0.4以下，若您解决了这些问题，欢迎交流！
 
 我现在也是遇到这种问题，不知道你解决了没有
 
 现在我解决了多类别问题，在你所使用的backbone的网络代码中将hm更改为你的类别数，之后将其他地方的num_class更改你的类别数，就可以了
 
 请问你们的map是怎么计算的，又代码提供吗？实在实现不了
 
 —
 You are receiving this because you commented.
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Z-ztao** [comment]
我也没有。



| |
sunshinetaoz
|
|
***@***.***
|
发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月26日 14:59 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ZeroE04/R-CenterNet] 多类别训练问题 (#8) |

请问你成功计算了MAP吗？？可以提供代码吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ZeroE04/R-CenterNet" ***@***.***&gt;;
发送时间:&nbsp;2021年11月26日(星期五) 下午2:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZeroE04/R-CenterNet] 多类别训练问题 (#8)





这样就行了。感觉计算旋转map又要另外的方法



| |
sunshinetaoz
|
|
***@***.***
|
发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***&gt; |
| 日期 | 2021年11月26日 14:49 |
| 收件人 | ***@***.***&gt; |
| 抄送至 | ***@***.******@***.***&gt; |
| 主题 | Re: [ZeroE04/R-CenterNet] 多类别训练问题 (#8) |

不好意思，我们目前还未解决多类别这个问题！-----当我们修改num_classes&gt;1时，最终预测类别Id一直等于2，mAP一直处于0.4以下，若您解决了这些问题，欢迎交流！

我现在也是遇到这种问题，不知道你解决了没有

现在我解决了多类别问题，在你所使用的backbone的网络代码中将hm更改为你的类别数，之后将其他地方的num_class更改你的类别数，就可以了

请问你们的map是怎么计算的，又代码提供吗？实在实现不了

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by singlestrong** [comment]
> 不好意思，我们目前还未解决多类别这个问题！-----当我们修改num_classes>1时，最终预测类别Id一直等于2，mAP一直处于0.4以下，若您解决了这些问题，欢迎交流！

请问你成功计算了MAP吗？？可以提供代码吗
